name: Build FluxPDF

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas PyPDF2 docx2pdf

      - name: Build EXE
        run: pyinstaller FluxPDF.spec --clean --noconfirm

      - name: Download & Install Inno Setup (fast mirror)
        shell: powershell
        run: |
          Invoke-WebRequest "https://github.com/vslavik/innosetup/releases/download/6.2.2/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
          Start-Process "innosetup.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait

      - name: Build Installer
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FluxPDF-Build
          path: |
            dist/FluxPDF/FluxPDF.exe
            installer/*.exe
